services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
                    - "@mailer"
                    - "%locale%"
                    - 5

    OC\PlatformBundle\DataFixtures\ORM\LoadCategory:
        tags: [doctrine.fixture.orm]
