<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function myFindAll()
    {
        //Methode 1: en passant par l'entitymanager
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('a')
            ->from($this->_entityName, 'a');

        //methode 2: en passant par le raccourci
        $queryBuilder = $this->createQueryBuilder('a');

        //la recuperation de query a partir du QueryBuilder
        $query = $queryBuilder->getQuery();

        //la recuperation des resultats
        $results = $query->getResult();

        return $results;

    }

    public function myFindOne($id)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.id = :id')->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }

    //une methode recupére touttes les annonces ecrites  par un auteur ayant une année donnée
    public function findByAuthorAndDate($author, $year)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.author = :author')->setParameter('author', $author)
            ->andWhere('a.date = :year')->setParmeter('year', $year)
            ->orderBy('a.date', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
