<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\DBAL\Query\QueryBuilder;
use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function getAdvertWithApplications()
    {
        $dq= $this->createQueryBuilder('a')
            ->leftJoin('a.applications','app')
            ->addSelect('app');

        return $dq->getQuery()->getResult();
    }
}
